version: '3.3'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - local

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    networks:
      - local
    environment:
      KAFKA_ADVERTISED_HOST_NAME: docker.for.mac.localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "tweets:4:1"
    depends_on:
      - zookeeper

networks:
  local:
